const $=s=>document.querySelector(s), content=$('#content'), notice=$('#notice'), dialog=$('#dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>String(v).replaceAll('-',' ').replaceAll('_',' ');
const browseTab='Discoveries and Opportunities';
const tabs=['Overview',browseTab,'Applications & Activity','Settings'];
const settingTabs=['My profile','Source preferences','Opportunity preferences','Automation controls','Connections'];
let setting='My profile',progress='Applications',jobView='discoveries',connected=false;
let jobPage={jobs:[],total:0,nextOffset:null},jobQuery='',jobSort='newest',catalogRequest=0,searchTimer;
const catalogJobs=new Map();
const embedded=new URLSearchParams(location.search).has('embedded');
document.body.classList.toggle('embedded',embedded);
const announce=payload=>{if(embedded)parent.postMessage({channel:'aura-apply',...payload},location.origin);};
const buildStatus=document.createElement('section');buildStatus.setAttribute('aria-label','Development safeguards');notice.before(buildStatus);
let state=null,tab='Overview',busy=false,devToken='',detail=null,preferenceEditor=null;
const isLocal=['localhost','127.0.0.1'].includes(location.hostname);
function message(text,error=false){notice.innerHTML=`<div class="notice ${error?'error':''}">${esc(text)}</div>`;if(dialog.open&&error){let box=dialog.querySelector('[role=alert]');if(!box){box=document.createElement('p');box.role='alert';box.className='risk';dialog.prepend(box);}box.textContent=text;}}
async function api(path,body){
 const res=await fetch(`/api/apply${path}`,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:{...(body===undefined?{}:{'Content-Type':'application/json','X-Aura-Apply':'1'}),...(devToken?{Authorization:`Bearer ${devToken}`}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});
 if([404,503].includes(res.status)||!res.headers.get('content-type')?.includes('application/json'))throw new Error('Aura Apply is not connected on this host yet.');
 const data=await res.json();if(!res.ok)throw new Error(`${pretty(data.error||'Request failed')}${data.fields?.length?': '+data.fields.join(', '):''}`);if(body!==undefined&&!['/jobs/list','/preferences/options'].includes(path))announce({type:'changed'});return data;
}
async function action(fn){if(busy)return;busy=true;content.setAttribute('aria-busy','true');try{await fn();}catch(e){message(e.message,true);}finally{busy=false;content.setAttribute('aria-busy','false');}}
async function refresh(){
 try{state=await api('/state');connected=true;notice.replaceChildren();render();announce({type:'summary',counts:{opportunities:matchedJobs().length,applications:state.applications.length,attention:state.applications.filter(a=>['manual','review','unknown'].includes(a.state)).length}});}
 catch(error){connected=false;state=null;detail=null;if(dialog.open)dialog.close();$('#dialog-content').replaceChildren();announce({type:'unavailable'});render();throw error;}
}
function matchedJobs(){return state.jobs.filter(j=>state.sources.some(s=>s.id===j.job.source&&s.enabled)&&(j.addedAt||['selected','review'].includes(j.disposition))&&(!j.job.expiresAt||Date.parse(j.job.expiresAt)>Date.now()));}
function unavailable(){
 const descriptions={Overview:'Your selected sources, relevant opportunities and application progress in one workspace.',[browseTab]:'Discover recent roles in related fields, then keep your preference matches and personally added opportunities together.','Applications & Activity':'Track prepared applications, your decisions, delivery receipts and background activity together.'};
 if(tab==='Settings'){
  content.innerHTML='<div class="settings-layout"><nav class="settings-tabs" aria-label="Apply settings">'+settingTabs.map(t=>'<button data-setting="'+t+'" '+(setting===t?'aria-current="page"':'')+'>'+t+'</button>').join('')+'</nav><section class="panel"><h2>'+esc(setting)+'</h2><p>'+esc({'My profile':'Your application details, confirmed experience, CV and professional documents.','Source preferences':'Choose which connected job sources are included in discovery.','Opportunity preferences':'Set roles, location, working arrangements, pay and exclusions.','Automation controls':'Choose discovery-only, guided review or permitted automated stages. Sending always respects your permissions.','Connections':'Manage authorised account connections and check service availability.'}[setting])+'</p><p class="muted">The private Apply service must be connected before these settings can be loaded or saved.</p><button data-do="retry">Retry connection</button></section></div>';return;
 }
 content.innerHTML='<section class="intro"><span class="eyebrow">BUILT-IN WORKSPACE</span><h2>'+esc(tab==='Overview'?'Your next opportunity, on your terms.':tab)+'</h2><p>'+esc(descriptions[tab])+'</p>'+(tab==='Overview'?'<div class="actions"><button data-tab="Opportunities">Explore opportunities</button><button data-tab="Settings">Set your preferences</button></div>':'')+'</section><div class="empty"><h3>Connect your private Apply service</h3><p>This window is ready. Your profile, job sources and applications are not connected on this host yet. No sample jobs or applicant details are displayed.</p><button data-do="retry">Retry connection</button></div>';
}
function pill(value){return `<span class="pill ${['selected','submitted','connected'].includes(value)?'good':['review','manual','unknown'].includes(value)?'warn':''}">${esc(pretty(value))}</span>`;}
function empty(title,text){return `<div class="empty"><h2>${esc(title)}</h2><p>${esc(text)}</p></div>`;}
function checked(value){return value?'checked':'';}
function options(values,selected){return values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(pretty(v))}</option>`).join('');}
function link(url,label){try{const u=new URL(url);if(u.protocol!=='https:')return '';if(u.hostname==='example.org'&&u.pathname.startsWith('/aura-apply-sample/'))return '<span class="tag">Fictional sample · not a platform listing</span>';return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;}catch{return '';}}
function go(next){if(next==='Discover'||next==='Discoveries'||next==='Opportunities'){jobView=next==='Opportunities'?'opportunities':'discoveries';next=browseTab;}if(next==='My profile'||next==='Sources'){setting=next==='Sources'?'Source preferences':'My profile';next='Settings';}if(next==='Applications'||next==='Activity'){progress=next;next='Applications & Activity';}if(!tabs.includes(next))return;tab=next;notice.replaceChildren();render();document.querySelector('main').scrollTop=0;}
function render(){
 $('#navigation').innerHTML=tabs.map(t=>`<button data-tab="${t}" ${t===tab?'aria-current="page"':''}>${t}</button>`).join('');$('#heading').textContent=tab;
 $('#run-status').textContent=!connected?'Not connected':state.preferences.paused?'Automation paused':state.capabilities.localWorkspace?'Local workspace':state.capabilities.automation?'Scheduled':'Manual';
 if(!connected){buildStatus.innerHTML='';unavailable();if(isLocal)content.insertAdjacentHTML('beforeend','<details class="panel"><summary>Local workspace connection</summary><form id="dev-form"><label>Local development token<input name="token" type="password" autocomplete="off" required></label><button>Unlock local workspace</button></form></details>');return;}
 buildStatus.innerHTML=state.capabilities.submissions?'':`<p class="service-status">${state.capabilities.liveDiscovery?'Discovery available':'Discovery not connected'} · Application sending off</p>`;
 ({Overview:overview,[browseTab]:opportunities,'Applications & Activity':applicationHub,Settings:settingsHub}[tab])();
}
function applicationHub(){
 if(progress==='Activity')activity();else applications();
 content.insertAdjacentHTML('afterbegin','<nav class="sub-tabs" aria-label="Application views">'+['Applications','Activity'].map(t=>'<button data-progress="'+t+'" '+(progress===t?'aria-current="page"':'')+'>'+t+'</button>').join('')+'</nav>');
 if(progress==='Activity')content.insertAdjacentHTML('beforeend',serviceActivity());
}
function serviceActivity(){
 const available=state.sources.filter(s=>s.ready&&s.enabled);
 return `<section class="panel"><h2>Live search sources</h2>${available.map(s=>`<div class="row"><div><b>${esc(s.name)}</b><p class="muted">${s.discovery==='feed'?'Public feed · no account login needed':'Authorised search API'}</p><small>${s.last_scan?'Last fetched '+esc(new Date(s.last_scan).toLocaleString()):'Not searched yet'}</small>${s.last_error?`<p class="warn">${esc(pretty(s.last_error))}</p>`:''}</div>${link(s.url,'Source')}</div>`).join('')||'<p>No search source is enabled.</p>'}<button data-tab="Sources">Manage source preferences</button></section>
 <section class="panel"><h2>Your accounts & hosting</h2>${[['Workspace','Aura AI → Aura Apply'],['Data storage',state.workspace.storage==='local'?'This computer · not synced to Cloudflare':'Dedicated Aura Apply database'],['Aura account',state.capabilities.localWorkspace?'Local workspace':state.account.email],['Gmail',state.connections.some(c=>c.provider==='gmail')?'Connected (send only)':'Not connected'],['Platform sign-ins','Not connected'],['Background scheduler',state.capabilities.automation?'Available · follows your controls':'Off · manual actions only'],['Application sending',state.capabilities.submissions?'Enabled':'Disabled']].map(([a,b])=>`<div class="row"><span>${esc(a)}</span><small>${esc(b)}</small></div>`).join('')}<button data-open-setting="Connections">Manage connections</button><p class="muted">Public feeds do not sign into your job-site accounts. Website submission and inbox monitoring are not connected.</p></section>`;
}
function settingsHub(){
 if(setting==='My profile')profile();else if(setting==='Source preferences')sources();else settings();
 if(!['My profile','Source preferences'].includes(setting)){
  const form=$('#settings-form'),panels=form.querySelectorAll(':scope > .panel');
  panels[0].hidden=setting!=='Opportunity preferences';panels[1].hidden=setting!=='Automation controls';
  form.hidden=setting==='Connections';
  form.nextElementSibling.hidden=setting!=='Connections';
  if(setting==='Opportunity preferences')panels[0].insertAdjacentHTML('beforeend','<button type="submit" class="primary">Save opportunity preferences</button>');
 }
 const body=document.createElement('div');body.className='settings-body';body.append(...content.childNodes);
 const layout=document.createElement('div');layout.className='settings-layout';
 const navigation=document.createElement('nav');navigation.className='settings-tabs';navigation.setAttribute('aria-label','Apply settings');
 navigation.innerHTML=settingTabs.map(t=>'<button data-setting="'+t+'" '+(setting===t?'aria-current="page"':'')+'>'+t+'</button>').join('');
 layout.append(navigation,body);content.append(layout);
 if(preferenceEditor&&$('#settings-form'))preferenceEditor.bind($('#settings-form'));
}
function overview(){
 const counts={discover:state.jobs.length,select:state.jobs.filter(j=>j.disposition==='selected').length,review:state.applications.filter(a=>['review','manual','approved'].includes(a.state)).length,apply:state.applications.filter(a=>a.state==='submitted').length};
 const needs=state.applications.filter(a=>['manual','review','unknown'].includes(a.state));
 content.innerHTML=`<div class="intro"><p class="eyebrow">ONE MIND. A CLEAR NEXT STEP.</p><h2>Your real opportunities.<br>Your private workspace.</h2><p>Search genuine vacancies, inspect the source and see how they fit your preferences. No sample jobs, and no CV needed to start searching.</p><div class="actions"><button class="primary" data-do="search-live" ${state.capabilities.liveDiscovery&&state.sources.some(s=>s.ready&&s.enabled)?'':'disabled'}>Search real vacancies</button><button data-tab="Opportunities">View opportunities (${matchedJobs().length})</button><button data-open-setting="Opportunity preferences">Edit search preferences</button><button data-tab="My profile">${state.profile?'Edit your profile':'Set up your profile'}</button></div><details><summary>How discovery works</summary><p class="muted">Search processes a bounded batch from up to ${Math.min(3,state.limits.parallelSources)} enabled sources. Repeated searches respect refresh times. This is not an exhaustive search of every registered platform.</p></details></div>
 <div class="cards">${[['Auto Discover',counts.discover,'Listings in view'],['Auto Select',counts.select,'Clear matches'],['Auto Review',counts.review,'Prepared / awaiting action'],['Auto Apply',counts.apply,'Receipted email submissions']].map(([name,count,label],i)=>`<div class="card"><small>0${i+1} · ${name}</small><b class="number">${count}</b><small>${label}</small></div>`).join('')}</div>
 <div class="grid"><section class="panel"><div class="split-title"><h2>Your attention</h2>${pill(needs.length+' items')}</div>${needs.length?needs.slice(0,5).map(a=>{const j=state.jobs.find(j=>j.id===a.job_id)?.job;return `<div class="row"><div><b>${esc(j?.title||'Application')}</b><p class="muted">${esc(j?.company||'')}</p>${pill(a.state)}</div><button data-detail="${a.id}">Review</button></div>`;}).join(''):'<p class="muted">No pending applications. Start with your profile and connected sources.</p>'}</section>
 <section class="panel"><h2>Connection health</h2>${[['Profile',state.profile?.consent.applicationUse?'Confirmed':'Needs your details'],['Search feeds',state.sources.filter(s=>s.ready&&s.enabled).length+' enabled'],['Gmail',state.connections.some(c=>c.provider==='gmail')?'Connected':'Not connected'],['Live delivery',state.capabilities.submissions?'Enabled':'Disabled at deployment'],['Website browser', 'Not connected'],['Inbox monitoring','Not connected']].map(([a,b])=>`<div class="row"><span>${a}</span><small>${b}</small></div>`).join('')}</section></div>
 <div class="panel"><h2>Honest automation</h2><p class="muted">${esc(state.capabilities.submission)} Source access, employer requirements and your permissions still apply. Nothing is marked submitted without a provider receipt. Counts show the latest ${state.limits.stateWindow} records.</p><div class="actions"><button data-do="pause" ${state.capabilities.automation?'':'disabled'}>${state.preferences.paused?'Resume configured stages':'Pause automation'}</button><button data-do="tick" ${state.capabilities.automation?'':'disabled'}>Run a queue tick</button><button data-open-setting="Automation controls">Automation controls</button></div></div>`;
}
function opportunities(){
 const live=state.sources.filter(s=>s.enabled&&s.ready).length,selected=state.sources.filter(s=>s.enabled).length;
 content.innerHTML=`<nav class="sub-tabs" aria-label="Opportunity views">${[['discoveries','Discover'],['opportunities','Opportunities']].map(([id,label])=>`<button data-job-view="${id}" ${jobView===id?'aria-current="page"':''}>${label}</button>`).join('')}</nav>
 <section class="browse-intro"><h2>${jobView==='discoveries'?'A wider view of what’s new.':'Your matches. Your choices.'}</h2><p class="muted">${jobView==='discoveries'?'Posted within the last three months, connected to your confirmed background or selected fields. These roles may fall outside your pay, seniority or location preferences. Undated and expired listings are not shown here.':'Matching roles plus discoveries you personally add. No posting-age cutoff: older listings can appear, but expired roles are excluded. Unknown closing dates need checking with the employer.'}</p><p class="coverage">${live} live-connected / ${selected} selected sources · <button data-tab="Sources">View source coverage</button></p><div class="actions"><button class="primary" data-do="search-live" ${state.capabilities.liveDiscovery&&live?'':'disabled'}>${jobView==='discoveries'?'Find recent discoveries':'Search matching opportunities'}</button><button data-do="reassess">Recheck fit</button><button data-do="import">Import a listing</button></div><small>Each search checks a bounded batch from every selected, connected source. Further searches continue other fields and result pages. Feed refresh times apply. Background discovery is ${state.capabilities.automation&&!state.preferences.paused?'configured':'paused/off'}; nothing is applied for here.</small></section>
 <form id="job-filter-form" class="job-filters"><input class="search" id="job-search" aria-label="Filter opportunities" maxlength="200" value="${esc(jobQuery)}" placeholder="Title, employer, location or keyword"><select id="job-sort" aria-label="Sort jobs">${options(jobView==='discoveries'?['newest']:['newest','match'],jobSort)}</select><button>Search saved</button></form><p id="job-count" role="status"></p><div id="jobs-list" aria-busy="true"><p class="muted">Loading real listings…</p></div><div class="actions"><button data-do="more-jobs" hidden>Show more</button></div>`;
 loadJobs().catch(error=>{if(tab===browseTab){message(error.message,true);$('#jobs-list').innerHTML='<p>Listings could not be loaded. Please retry.</p>';$('#jobs-list').setAttribute('aria-busy','false');}});
}
async function loadJobs(more=false){
 const token=++catalogRequest,view=jobView,result=await api('/jobs/list',{view,offset:more?jobPage.nextOffset??0:0,query:jobQuery,sort:jobSort});
 if(token!==catalogRequest||tab!==browseTab||view!==jobView)return;
 if(!more)catalogJobs.clear();for(const row of result.jobs)catalogJobs.set(row.id,row);
 jobPage={...result,jobs:more?[...jobPage.jobs,...result.jobs]:result.jobs};drawJobs();
}
const shown=v=>v&&v!=='unknown'?pretty(v):'Not provided';
const dateLabel=v=>v&&Number.isFinite(Date.parse(v))?new Date(v).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'Not provided';
function salaryLabel(job){const s=job.salary;if(!s)return job.details?.salaryText||'Not provided';const amount=n=>`${s.currency} ${Number(n).toLocaleString()}`;return `${amount(s.min)}${s.max&&s.max!==s.min?' – '+amount(s.max):''} / ${s.period}${s.estimated?' (source estimate)':''}`;}
function jobFacts(row){const j=row.job,d=j.details||{};return `<dl class="job-facts">${[['Pay',salaryLabel(j)],['Location',j.location||'Not provided'],['Working arrangement',shown(j.workMode)],['Contract',shown(j.employmentType)+(j.permanent===true?' · Permanent':j.permanent===false?' · Not permanent':' · Permanence unconfirmed')],['Posted',dateLabel(j.publishedAt)],['Closing date',j.expiresAt?dateLabel(j.expiresAt):'Not provided · confirm still open'],['Seniority',d.seniority?.join(', ')||'Not provided'],['Eligible countries',j.countries?.join(', ')||'Not provided']].map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl>`;}
function jobSections(job){const d=job.details||{};return `${[['Requirements',d.requirements],['Responsibilities',d.responsibilities],['Benefits',d.benefits],['Skills / source tags',d.skills?.join(', ')],['Time zones',d.timezones?.join(', ')]].map(([label,text])=>`<section class="job-section"><h3>${label}</h3><p class="source-copy">${esc(text||'Not provided separately. Check the source description below.')}</p></section>`).join('')}<section class="job-section"><h3>Source description${d.descriptionKind==='excerpt'?' · excerpt':''}</h3><p class="source-copy">${esc(job.description||'Not provided')}</p><small>Source-supplied content, displayed as text. Section extraction is not verification of every requirement. Consult the original listing before applying.</small></section>`;}
function fitDetails(row){return `<p>${row.addedAt?'<span class="pill good">Added by you</span> ':''}${row.disposition==='excluded'?'<span class="pill warn">Outside your preferences</span>':pill(row.disposition)}</p>${row.decision?`<p>${esc(row.decision.reasons.join(' '))}</p><p class="muted">${esc(row.decision.uncertainties.join(' '))}</p>`:''}${row.addedAt&&row.disposition==='excluded'?'<p class="risk">Saved for your consideration. Adding this role does not override your requirements or enable automatic applications.</p>':''}`;}
function drawJobs(){
 $('#job-count').textContent=`${jobPage.total} ${jobView==='discoveries'?'recent discoveries':'opportunities'} · ${jobPage.jobs.length} shown${jobView==='discoveries'?' · Based on '+jobPage.basis:''}`;
 $('#job-count').insertAdjacentHTML('beforeend','<span class="data-attribution"> Data from '+[...new Set(jobPage.jobs.map(row=>row.job.source))].map(id=>{const source=state.sources.find(s=>s.id===id);return link(source?.url,source?.name||id);}).join(' · ')+'</span>');
 $('#jobs-list').setAttribute('aria-busy','false');
 $('#jobs-list').innerHTML=jobPage.jobs.length?jobPage.jobs.map(row=>{const {id,job}=row;return `<article class="panel job-card"><div class="split-title"><div><span class="tag">${esc(job.company)}</span><h2>${esc(job.title)}</h2></div></div>${jobFacts(row)}<h3>About the role</h3><p class="job-excerpt">${esc((job.description||'Not provided').slice(0,360))}${job.description?.length>360?'…':''}</p>${fitDetails(row)}<div class="actions"><button data-job="${id}">Full job details</button><button data-shortlist="${id}" data-added="${row.addedAt?'false':'true'}">${row.addedAt?'Remove personal save':'Add to opportunities'}</button>${link(job.url,`Source: ${state.sources.find(s=>s.id===job.source)?.name||job.source}`)}</div><small>${row.lastSeenAt?'Last retrieved '+esc(dateLabel(row.lastSeenAt)):'Imported listing · availability not verified'} · Original posting date retained</small></article>`;}).join(''):empty(jobView==='discoveries'?'No recent discoveries in this search':'No matching opportunities in this search','Search real vacancies above, review your selected fields, or import an authorised listing. Missing dates and expired listings are never relabelled as fresh.');
 $('[data-do="more-jobs"]').hidden=jobPage.nextOffset===null;
}
function jobDialog(row){const {id,job}=row,source=state.sources.find(s=>s.id===job.source);showDialog(`<span class="eyebrow">${link(source?.url,`Data from ${source?.name||job.source}`)}</span><h2>${esc(job.title)}</h2><p>${esc(job.company)}</p>${jobFacts(row)}${fitDetails(row)}${jobSections(job)}<div class="actions">${link(job.url,'Original listing')}${link(job.applyUrl,'Employer / application link')}<button data-shortlist="${id}" data-added="${row.addedAt?'false':'true'}">${row.addedAt?'Remove personal save':'Add to opportunities'}</button><button data-prepare="${id}" ${row.disposition==='excluded'||!state.profile?.consent.applicationUse?'disabled':''}>Prepare application</button><button data-analyse="${id}" ${state.capabilities.cloudAi?'':'disabled'}>AI fit review</button></div>`);}
function applications(){content.innerHTML=`<p class="muted">A draft is not a submission. Unknown delivery outcomes stay blocked to prevent duplicate applications.</p>${state.applications.length?state.applications.map(a=>{const j=state.jobs.find(j=>j.id===a.job_id)?.job;return `<div class="panel row"><div><h3>${esc(j?.title||'Application')}</h3><p class="muted">${esc(j?.company||'')} · ${esc(new Date(a.updated_at).toLocaleString())}</p>${pill(a.state)}</div><button data-detail="${a.id}">Open application</button></div>`;}).join(''):empty('A clear record of every application','Prepared applications, approvals and delivery receipts will appear here.')}`;}
function profile(){
 const p=state.profile||{preferredName:'',email:state.capabilities.localWorkspace?'':state.account.email,phone:'',location:'',rightToWorkCountries:[],sponsorshipRequired:false,availableFrom:'',workHistoryComplete:false,evidence:[],consent:{applicationUse:false,cloudAiAnalysis:false}};
 content.innerHTML=`<form id="profile-form"><div class="panel"><h2>Your private application profile</h2><p class="muted">Editable professional details. Identity documents, passport numbers and account passwords do not belong here. Verified Aura-profile import is not connected yet.</p><div class="grid"><div><label>Preferred name<input name="preferredName" required value="${esc(p.preferredName)}"></label><label>Application email<input name="email" type="email" required value="${esc(p.email)}"></label><label>Phone number<input name="phone" type="tel" value="${esc(p.phone)}"></label><label>Town / city<input name="location" required value="${esc(p.location)}"></label></div><div><label>Legal name, if needed<input name="legalName" value="${esc(p.legalName)}"></label><label>Right-to-work countries (comma separated)<input name="countries" value="${esc(p.rightToWorkCountries.join(', '))}"></label><label>Available from<input name="availableFrom" value="${esc(p.availableFrom)}" placeholder="Immediately"></label><label class="check"><input type="checkbox" name="sponsorshipRequired" ${checked(p.sponsorshipRequired)}>I require sponsorship</label></div></div></div>
 <div class="panel"><div class="split-title"><h2>Evidence, skills & credits</h2><button type="button" data-do="add-evidence">Add evidence</button></div><p class="muted">Add one truthful fact per entry: roles and dates, project responsibilities, software skills, degree details, release credits or portfolio links. Only entries you confirm can enter application drafts.</p><div id="evidence-list">${p.evidence.map(evidenceRow).join('')}</div></div>
 <div class="panel"><label class="check"><input name="workHistoryComplete" type="checkbox" ${checked(p.workHistoryComplete)}>My relevant work history is complete and the facts above are accurate.</label><label class="check"><input name="applicationUse" type="checkbox" ${checked(p.consent.applicationUse)}>Use this private profile to prepare job applications; sending still follows my application controls.</label><label class="check"><input name="cloudAiAnalysis" type="checkbox" ${checked(p.consent.cloudAiAnalysis)}>Allow Cloudflare AI to analyse confirmed professional evidence and vacancy text. Avoid putting sensitive data in evidence text.</label><button class="primary" type="submit">Save private profile</button></div></form>
 <section class="panel"><h2>CV & professional documents</h2><p class="muted">Encrypted storage for PDF, DOCX or text. Up to 250 KB per file and 10 files in this pilot. Upload does not imply consent to send. No automated passport or identity-document handling.</p><input id="document-file" type="file" accept=".pdf,.docx,.txt" aria-label="Upload a professional document">${state.documents.map(d=>`<div class="row"><b>${esc(d.filename)}</b><small>${Math.ceil(d.byte_size/1024)} KB</small></div>`).join('')}</section>`;
}
function evidenceRow(e={id:crypto.randomUUID(),kind:'skill',text:'',url:'',confirmed:false}){return `<div class="evidence-row" data-evidence="${esc(e.id)}"><div><select name="kind" aria-label="Evidence type">${options(['skill','education','employment','project','portfolio','certificate','statement'],e.kind)}</select><label><input name="confirmed" type="checkbox" ${checked(e.confirmed)}>Confirmed</label></div><div><textarea name="text" aria-label="Evidence details" maxlength="4000">${esc(e.text)}</textarea><input name="url" type="url" aria-label="Evidence link" placeholder="Optional portfolio or project link" value="${esc(e.url)}"></div></div>`;}
const openSourceGroups=new Set();
function sources(){
 const groups=state.sourceGroups||[...new Set(state.sources.map(s=>s.group))].map(id=>({id,name:id}));
 const sourceCard=s=>`<section class="panel"><div class="split-title"><label class="source-name"><input data-source="${esc(s.id)}" type="checkbox" ${checked(s.enabled)}>${esc(s.name)}</label>${pill(s.ready?'live search':s.discovery==='key'?'API key required':s.discovery==='employer'?'employer setup':s.discovery==='deferred'?'access required':'open / import')}</div><p>${esc(s.note||'')}</p><div class="actions">${link(s.url,s.group==='Employer'?'Provider website':'Open source')}<button data-import-source="${esc(s.id)}">Import listing</button></div><small>${s.last_scan?'Last successful search: '+esc(new Date(s.last_scan).toLocaleString()):s.ready?'Ready to search':'Automatic search not connected'}</small>${s.last_error?`<p class="warn">${esc(pretty(s.last_error))}</p>`:''}</section>`;
 content.innerHTML=`<p class="muted">${state.sources.length} platforms and systems, organised by category. Selection is personal to your account; it does not supply API credentials or activate automatic applications.</p><div class="actions"><button data-do="all-sources">Select all sources</button><button data-do="no-sources">Deselect all</button></div><p class="coverage">${state.sources.filter(s=>s.enabled).length} selected · ${state.sources.filter(s=>s.ready&&s.enabled).length} live-connected. Other platforms can be opened and their authorised listings imported into the same job format.</p>${groups.map(group=>{const members=state.sources.filter(s=>s.group===group.id),selected=members.filter(s=>s.enabled).length;return `<section class="source-category panel"><div class="category-heading"><input type="checkbox" data-source-group="${esc(group.id)}" aria-label="Select all: ${esc(group.name)}" ${checked(selected===members.length&&selected>0)}><h3>${esc(group.name)}</h3><small>${selected}/${members.length}</small></div><details data-source-category="${esc(group.id)}" ${openSourceGroups.has(group.id)?'open':''}><summary>Show platforms</summary><div class="source-grid">${members.map(sourceCard).join('')}</div>${state.sources.some(s=>s.relatedGroups?.includes(group.id))?'<p class="muted">Also relevant: '+state.sources.filter(s=>s.relatedGroups?.includes(group.id)).map(s=>esc(s.name)+' — managed under '+esc(groups.find(g=>g.id===s.group)?.name||s.group)).join('; ')+'. Its shared selection is not changed by this category checkbox.</p>':''}</details></section>`;}).join('')}`;
 for(const input of content.querySelectorAll('[data-source-group]')){const members=state.sources.filter(s=>s.group===input.dataset.sourceGroup),selected=members.filter(s=>s.enabled).length;input.indeterminate=selected>0&&selected<members.length;}
 for(const details of content.querySelectorAll('[data-source-category]'))details.addEventListener('toggle',()=>{if(details.open)openSourceGroups.add(details.dataset.sourceCategory);else openSourceGroups.delete(details.dataset.sourceCategory);});
}
const choice=(label,name,values,selected)=>`<fieldset><legend>${label}</legend><div class="choices">${values.map(v=>`<label><input type="checkbox" name="${name}" value="${esc(v)}" ${checked(selected.includes(v))}>${esc(pretty(v))}</label>`).join('')}</div></fieldset>`;
function settings(){const p=state.preferences;preferenceEditor=window.AuraPreferences.create({preferences:p,metadata:state.preferenceOptions,api});content.innerHTML=`<form id="settings-form"><div class="panel">${preferenceEditor.html}</div>
 <div class="panel"><h2>Automation controls</h2><label>Mode<select name="mode">${options(['assisted','guided','automated'],p.mode)}</select></label>${[['autoDiscover','Auto Discover'],['autoSelect','Auto Select'],['autoReview','Auto Review'],['autoApply','Auto Apply'],['humanApproval','Require human review before delivery'],['paused','Pause all background work']].map(([n,l])=>`<label class="check"><input type="checkbox" name="${n}" ${checked(p[n])}>${l}</label>`).join('')}<p class="risk">Turning human review off never bypasses identity checks, assessments, legal declarations, payments, CAPTCHA, unsupported sign-in or platform restrictions. The current email adapter still requires you to verify each recipient and exact payload.</p><button class="primary">Save preferences</button></div></form>
 <div class="panel"><h2>Connections & capacity</h2><p class="muted">Free pilot: ${state.limits.feedRequestsPerDay} source requests and ${state.limits.emailAttemptsPerDay} email attempts per day for this deployment. Failed attempts consume capacity. These are conservative product limits, not guaranteed provider allowances. Paid billing and upgrades are not activated.</p><div class="actions"><button data-do="gmail-connect" ${state.capabilities.gmailConfigured?'':'disabled'}>Connect Gmail (send only)</button><button data-do="gmail-disconnect">Disconnect Gmail</button><button data-do="export">Export profile & preferences</button></div></div>`;}
function activity(){content.innerHTML=`<div class="panel"><h2>Platform queues</h2><div class="table-wrap"><table><thead><tr><th>Platform</th><th>Stage</th><th>Status</th><th>Count</th></tr></thead><tbody>${state.queues.map(q=>`<tr><td>${esc(q.source)}</td><td>${esc(q.stage)}</td><td>${esc(q.status)}</td><td>${q.count}</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><h2>Activity log</h2>${state.events.length?state.events.map(e=>`<div class="row"><div><p>${esc(e.message)}</p><small>${esc(e.kind)} · ${esc(new Date(e.created_at).toLocaleString())}</small></div></div>`).join(''):'<p class="muted">No activity yet.</p>'}</div>`;}
function showDialog(html){
 $('#dialog-content').innerHTML=html;
 const imported=$('#import-form');if(imported){imported.querySelector('[name="description"]').closest('label').insertAdjacentHTML('afterend',`<div class="grid"><label>Posting date, if stated<input name="publishedAt" type="date"></label><label>Closing date, if stated<input name="expiresAt" type="date"></label></div>${[['requirements','Requirements'],['responsibilities','Responsibilities'],['benefits','Benefits']].map(([name,label])=>`<label>${label}, if stated<textarea name="${name}" maxlength="10000"></textarea></label>`).join('')}`);}
 const form=$('#email-form'),approved=detail?.approvedEnvelope;
 if(form&&approved){for(const name of ['to','subject','body'])form.elements[name].value=approved[name];for(const input of form.querySelectorAll('input[type=checkbox]'))input.checked=input.name==='documentIds'?approved.documentIds.includes(input.value):approved[input.name]===true;}
 dialog.showModal();
}
async function openApplication(applicationId){
 detail=await api('/applications/detail',{applicationId});const p=detail.package;const job=state.jobs.find(j=>j.id===detail.job_id)?.job;
 showDialog(`<p class="eyebrow">APPLICATION / ${esc(detail.state)}</p><h2>${esc(p.title)}</h2><p>${esc(p.note)}</p>${detail.receipt_json?`<pre>${esc(JSON.stringify(JSON.parse(detail.receipt_json),null,2))}</pre>`:''}<details><summary>Prepared evidence-based CV sections</summary><ul>${p.cvSections.map(e=>`<li>${esc(e.text)}</li>`).join('')}</ul></details><p class="muted">${esc(JSON.parse(detail.reasons_json).join(' '))}</p>${link(job?.applyUrl,'Open genuine employer application')}${['submitted','submitting','unknown'].includes(detail.state)?'<p class="risk">This application has been attempted. Automatic re-sending is blocked. Check the provider receipt or your Sent mail.</p>':`<form id="email-form"><h3>Employer email application</h3><p class="muted">Only use an address published by this employer for this vacancy. This is not a workaround for a platform’s restricted application form.</p><label>Verified recruitment email<input name="to" type="email" required value="${esc(job?.recipientEmail||'')}"></label><label>Subject<input name="subject" required value="${esc(p.title)}" maxlength="250"></label><label>Application message<textarea name="body" rows="10" required>${esc(p.coverNote)}</textarea></label>${state.documents.length?`<fieldset><legend>Choose exact attachments</legend>${state.documents.map(d=>`<label><input type="checkbox" name="documentIds" value="${d.id}">${esc(d.filename)}</label>`).join('')}</fieldset>`:'<p class="warn">No CV uploaded. Add a professional document to your profile if the employer needs one.</p>'}${[['employerAcceptsEmail','This employer explicitly accepts email applications for this vacancy.'],['recipientVerified','I verified this exact email address against the genuine employer listing.'],['factsVerified','I reviewed this message and the chosen documents; every claim is accurate.'],['requirementsReviewed','I checked the pay, paid hours, location, eligibility and job requirements.'],['noProtectiveStep','No outstanding identity check, assessment, declaration, payment or other protected step is being bypassed.']].map(([n,l])=>`<label class="check"><input type="checkbox" name="${n}" required>${l}</label>`).join('')}<div class="actions"><button class="primary">Approve this exact email</button><button type="button" data-send="${detail.id}" ${detail.state==='approved'&&state.capabilities.submissions?'':'disabled'}>Send approved email</button><button type="button" data-cancel="${detail.id}">Cancel application</button></div></form>`}`);
}
function importDialog(){showDialog(`<h2>Import an opportunity</h2><p class="muted">Paste the real vacancy details. Missing facts stay unknown; Aura will not guess.</p><form id="import-form"><label>Source<select name="source">${state.sources.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><div class="grid"><label>Job title<input name="title" required></label><label>Employer<input name="company" required></label></div><label>Original listing URL<input name="url" type="url" required></label><label>Application URL<input name="applyUrl" type="url" required></label><label>Location<input name="location" required></label><label>Eligible countries, if listed<input name="countries"></label><label>Description<textarea name="description" rows="7" required></textarea></label><div class="grid"><label>Working arrangement<select name="workMode">${options(['unknown','remote','hybrid','onsite'],'unknown')}</select></label><label>Employment type<select name="employmentType">${options(['unknown','full-time','part-time','contract','freelance','internship'],'unknown')}</select></label><label>Permanent contract<select name="permanent"><option value="unknown">Not confirmed</option><option value="true">Yes</option><option value="false">No</option></select></label><label>Pay floor, if stated<input name="pay" type="number" min="0" step=".01"></label><label>Currency<input name="currency" value="GBP" maxlength="3"></label><label>Pay period<select name="period">${options(['hour','year','month','day'],'year')}</select></label><label>Paid hours per week, if stated<input name="hoursPerWeek" type="number" step=".25" min="1" max="100"></label><label>Paid hours per day, if stated<input name="hoursPerDay" type="number" step=".25" min="1" max="24"></label></div><button class="primary">Import and assess</button></form>`);}
document.addEventListener('click',e=>{const target=e.target.closest('button');if(target?.type==='submit'&&target.form&&!target.dataset.do)return;action(async()=>{
 const t=e.target.closest('button');if(!t)return;
 if(t.dataset.tab){go(t.dataset.tab);return;}
 if(t.dataset.openSetting){setting=t.dataset.openSetting;go('Settings');return;}
 if(t.dataset.setting){setting=t.dataset.setting;render();return;}
 if(t.dataset.progress){progress=t.dataset.progress;render();return;}
 if(t.dataset.jobView){jobView=t.dataset.jobView;jobSort='newest';render();return;}
 if(t.dataset.do==='retry'){await refresh();return;}if(t.id==='close-dialog'){dialog.close();return;}if(t.id==='refresh'){await refresh();return;}
 if(t.id==='appearance'){const dark=matchMedia('(prefers-color-scheme: dark)').matches;const current=document.documentElement.dataset.theme|| (dark?'dark':'light');document.documentElement.dataset.theme=current==='dark'?'light':'dark';return;}
 if(!connected&&t.id!=='close-dialog')return;
 if(t.dataset.detail){await openApplication(t.dataset.detail);return;}
 if(t.dataset.prepare){const r=await api('/jobs/prepare',{jobId:t.dataset.prepare});await refresh();await openApplication(r.id);return;}
 if(t.dataset.analyse){const r=await api('/jobs/analyse',{jobId:t.dataset.analyse});showDialog(`<h2>AI fit review</h2><p>${esc(r.summary)}</p><ul>${r.concerns.map(c=>`<li>${esc(c)}</li>`).join('')}</ul><p class="muted">Advisory only. Hard preferences and factual verification remain in force.</p>`);return;}
 if(t.dataset.job){const j=catalogJobs.get(t.dataset.job)||state.jobs.find(j=>j.id===t.dataset.job);if(j)jobDialog(j);return;}
 if(t.dataset.shortlist){await api('/jobs/shortlist',{jobId:t.dataset.shortlist,added:t.dataset.added==='true'});if(dialog.open)dialog.close();await loadJobs();message(t.dataset.added==='true'?'Added to Opportunities. Your application requirements are unchanged.':'Personal save removed. A matching role can still appear in Opportunities.');return;}
 if(t.dataset.importSource){importDialog();$('#import-form [name="source"]').value=t.dataset.importSource;return;}
 if(t.dataset.send){const r=await api('/applications/send',{applicationId:t.dataset.send});dialog.close();await refresh();message(`Delivery status: ${r.state}`);return;}
 if(t.dataset.cancel){await api('/applications/cancel',{applicationId:t.dataset.cancel});dialog.close();await refresh();return;}
 switch(t.dataset.do){
 case 'search-live':{const mode=tab===browseTab?jobView:'opportunities',sources=state.sources.filter(s=>s.ready&&s.enabled).sort((a,b)=>String(a.next_scan).localeCompare(String(b.next_scan))).map(s=>s.id),batchSize=Math.min(3,state.limits.parallelSources||2),results=[];if(!sources.length)throw new Error('No selected source has a live connection yet. Open Source preferences to check setup requirements.');for(let i=0;i<sources.length;i+=batchSize){message(`Searching connected sources ${i+1}–${Math.min(i+batchSize,sources.length)} of ${sources.length}…`);const r=await api('/discovery/run',{sources:sources.slice(i,i+batchSize),mode});results.push(...r.results);}await refresh();go(mode==='discoveries'?'Discover':'Opportunities');message(results.map(x=>`${state.sources.find(s=>s.id===x.source)?.name||x.source}: ${x.status==='fetched'?x.saved+' real records processed'+(x.query?' · '+pretty(x.query)+', page '+x.page:''):x.status==='cached'?(x.error?pretty(x.error)+'; ':'')+'next check '+new Date(x.nextScan).toLocaleString():x.status==='running'?'search already running':pretty(x.error)}`).join(' · ')+'. No applications sent.',results.every(x=>x.status==='failed'));break;}
 case 'more-jobs':await loadJobs(true);break;
 case 'all-sources':case 'no-sources':await api('/sources/all',{enabled:t.dataset.do==='all-sources'});await refresh();break;
 case 'pause':await api('/preferences',{version:state.account.version,preferences:{...state.preferences,paused:!state.preferences.paused}});await refresh();break;
 case 'tick':{const r=await api('/tick',{});await refresh();message(r.reason?pretty(r.reason):`${r.processed} queued tasks processed.`);break;}
 case 'reassess':{let r=await api('/jobs/reassess',{}),assessed=r.assessed;while(r.nextCursor){r=await api('/jobs/reassess',{cursor:r.nextCursor,version:r.version});assessed+=r.assessed;}await refresh();message(`${assessed} saved vacancies rechecked. Existing applications unchanged; none sent.`);break;}
 case 'import':importDialog();break;
 case 'add-evidence':$('#evidence-list').insertAdjacentHTML('beforeend',evidenceRow());break;
 case 'gmail-connect':{const r=await api('/gmail/connect',{});location.assign(r.url);break;}
 case 'gmail-disconnect':{const r=await api('/gmail/disconnect',{});await refresh();message(r.note);break;}
 case 'export':{const data=await api('/export',{}),url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='aura-apply-private-export.json';a.click();URL.revokeObjectURL(url);break;}
 }
});});
document.addEventListener('input',e=>{if(e.target.id==='job-search'){jobQuery=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(tab===browseTab)loadJobs().catch(e=>message(e.message,true));},350);}if(e.target.closest('#email-form')){const send=dialog.querySelector('[data-send]');if(send)send.disabled=true;}});
document.addEventListener('change',e=>action(async()=>{
 const t=e.target;
 if(t.dataset.source){await api('/sources',{source:t.dataset.source,enabled:t.checked});await refresh();}
 if(t.dataset.sourceGroup){await api('/sources/group',{group:t.dataset.sourceGroup,enabled:t.checked});await refresh();}
 if(t.id==='job-sort'){jobSort=t.value;await loadJobs();}
 if(t.id==='document-file'&&t.files?.[0]){const f=t.files[0];if(f.size>250000)throw new Error('This pilot accepts documents up to 250 KB.');const bytes=new Uint8Array(await f.arrayBuffer());let raw='';for(let i=0;i<bytes.length;i+=8192)raw+=String.fromCharCode(...bytes.subarray(i,i+8192));const type=f.name.endsWith('.docx')?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':f.name.endsWith('.pdf')?'application/pdf':'text/plain';await api('/documents',{filename:f.name,contentType:type,base64:btoa(raw),professionalDocument:true});await refresh();message('Professional document encrypted and saved.');}
}));
document.addEventListener('submit',e=>{e.preventDefault();action(async()=>{
 const form=e.target,d=new FormData(form),get=n=>String(d.get(n)||''),yes=n=>d.has(n),list=n=>get(n).split(',').map(x=>x.trim()).filter(Boolean);
 if(form.id==='dev-form'){devToken=get('token');await refresh();return;}
 if(form.id==='job-filter-form'){clearTimeout(searchTimer);await loadJobs();return;}
 if(form.id==='profile-form'){
 const evidence=[...form.querySelectorAll('[data-evidence]')].map(el=>({id:el.dataset.evidence,kind:el.querySelector('[name=kind]').value,text:el.querySelector('[name=text]').value,confirmed:el.querySelector('[name=confirmed]').checked,...(el.querySelector('[name=url]').value?{url:el.querySelector('[name=url]').value}:{})})).filter(e=>e.text.trim());
 await api('/profile',{version:state.account.version,profile:{preferredName:get('preferredName'),legalName:get('legalName'),email:get('email'),phone:get('phone'),location:get('location'),rightToWorkCountries:list('countries'),sponsorshipRequired:yes('sponsorshipRequired'),availableFrom:get('availableFrom'),evidence,workHistoryComplete:yes('workHistoryComplete'),consent:{applicationUse:yes('applicationUse'),cloudAiAnalysis:yes('cloudAiAnalysis'),inheritedFromAura:false}}});announce({type:'changed'});await refresh();message('Private profile saved. Previous approvals need a fresh review.');
 }else if(form.id==='settings-form'){
 const p=setting==='Opportunity preferences'?preferenceEditor.read():{...state.preferences};for(const n of ['autoDiscover','autoSelect','autoReview','autoApply','humanApproval','paused'])p[n]=yes(n);p.mode=get('mode');
 let r=await api('/preferences',{version:state.account.version,preferences:p}),assessed=r.assessed??0;let note='';
 try{while(r.nextCursor){r=await api('/jobs/reassess',{cursor:r.nextCursor,version:r.version});assessed+=r.assessed;}
 if(setting==='Opportunity preferences'&&state.capabilities.liveDiscovery)for(const mode of ['discoveries','opportunities']){const ids=state.sources.filter(s=>s.ready&&s.enabled).map(s=>s.id);for(let i=0;i<ids.length;i+=2){const scan=await api('/discovery/run',{sources:ids.slice(i,i+2),mode});const failed=(scan.results??[]).filter(x=>x.status==='failed'||x.error);if(failed.length)note+=' Some source checks need retrying: '+failed.map(x=>pretty(x.source)+': '+pretty(x.error||x.status)).join(', ')+'.';}}
 }catch(error){note=' Preferences are saved, but part of the refresh needs retrying: '+error.message;}
 await refresh();message(`Preferences saved. ${assessed} saved vacancies refreshed; existing applications and approvals unchanged. Connected searches respect source refresh limits.${note}`,!!note);
 }else if(form.id==='import-form'){
 const salary=get('pay')?{min:Number(get('pay')),currency:get('currency').toUpperCase(),period:get('period'),...(get('hoursPerWeek')?{hoursPerWeek:Number(get('hoursPerWeek'))}:{}),...(get('hoursPerDay')?{hoursPerDay:Number(get('hoursPerDay'))}:{})}:null;
 await api('/jobs/import',{source:get('source'),externalId:crypto.randomUUID(),title:get('title'),company:get('company'),url:get('url'),applyUrl:get('applyUrl'),description:get('description'),location:get('location'),countries:list('countries'),workMode:get('workMode'),employmentType:get('employmentType'),permanent:get('permanent')==='unknown'?null:get('permanent')==='true',salary,expiresAt:get('expiresAt')?get('expiresAt')+'T23:59:59.000Z':null,publishedAt:get('publishedAt')?get('publishedAt')+'T00:00:00.000Z':null,details:{...Object.fromEntries(['requirements','responsibilities','benefits'].filter(n=>get(n)).map(n=>[n,get(n)])),descriptionKind:'unknown'}});dialog.close();await refresh();message('Listing imported and assessed.');
 }else if(form.id==='email-form'){
 const envelope={to:get('to'),subject:get('subject'),body:get('body'),documentIds:d.getAll('documentIds')};for(const n of ['employerAcceptsEmail','recipientVerified','factsVerified','requirementsReviewed','noProtectiveStep'])envelope[n]=yes(n);
 await api('/applications/approve-email',{applicationId:detail.id,envelope});dialog.close();await refresh();message('Exact email approved. '+(state.preferences.autoApply&&state.preferences.mode==='automated'?'It is queued for the permitted delivery stage.':'Open the application to send it when live delivery is enabled.'));
 }
});});
window.addEventListener('message',event=>{
 if(event.origin!==location.origin||event.source!==parent||event.data?.channel!=='aura-module-host')return;
 if(event.data.type==='navigate')go(event.data.section);
 if(event.data.type==='refresh'&&connected&&!busy){
  // Do not erase an in-progress profile/preferences form in a second view.
  if(content.querySelector('form'))message('Data changed in another window. Refresh when you have finished your edits.');
  else action(refresh);
 }
});
document.addEventListener('pointerdown',()=>announce({type:'focus'}),{passive:true});
render();action(refresh);
