/* Structured preference editor. All IDs are verified again by the private API. */
window.AuraPreferences={create({preferences:p,metadata:m={},api}){
 const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const label=v=>String(v).replaceAll('-',' '),pick=(values,current)=>values.map(([id,name])=>`<option value="${escape(id)}" ${id===current?'selected':''}>${escape(name)}</option>`).join('');
 const days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
 const checks=(title,name,values,selected)=>`<fieldset><legend>${title}</legend><div class="choices">${values.map(v=>`<label class="check"><input type="checkbox" name="${name}" value="${v}" ${selected.includes(v)?'checked':''}>${label(v)}</label>`).join('')}</div></fieldset>`;
 const roles=(m.selectedRoles??(p.roleTargets??p.roleFamilies).map(id=>({id,label:label(id)}))).map(x=>({...x}));
 const places=(m.selectedLocations??p.locations.map(name=>({id:'custom:'+name,name,label:name+' (custom)'}))).map(x=>({...x}));
 const countries=[...p.countries],exclusions=(p.exclusions??[...(p.excludeTeaching?[{phrase:'teaching',scope:'title'}]:[]),...(p.excludeLiveAudio?['live sound','live audio','live event','stage technician','AV technician','equipment technician'].map(phrase=>({phrase,scope:'title'})):[])]).map(x=>({...x}));
 const availability=p.availability??{timezone:'Europe/London',days:days.map(day=>({day,mode:day==='sunday'&&p.sunday==='avoid'?'unavailable':'any',intervals:[]}))};
 const pay=p.pay??{amount:p.minimumHourlyGBP,currency:'GBP',period:'hour'},hours=p.workingHours??{paidWeeks:52,country:'',ageBand:'unspecified'};
 const currencyCodes=typeof Intl.supportedValuesOf==='function'?Intl.supportedValuesOf('currency'):['GBP','EUR','USD'];if(!currencyCodes.includes(pay.currency))currencyCodes.push(pay.currency);
 const tz=[...new Set([availability.timezone,...(m.timezones??[])])];
 const selector=(title,id,entries)=>`<label>${title}<select id="${id}"><option value="">Any</option>${pick(Object.entries(entries??{}),'')}</select></label>`;
 let form;const requests={roles:0,locations:0},timers={},results={roles:new Map(),locations:new Map()};
 const html=`<h2>Opportunity preferences</h2><p class="muted">Choose the work you want to do. Search understands recognised occupations and alternative titles—not arbitrary combinations of keywords. Uncertain duties, pay and eligibility stay marked for review.</p>
 <fieldset><legend>Roles & interests</legend><div id="role-chips" class="preference-chips" aria-label="Selected occupations"></div>
 <details id="role-picker"><summary>Add a role or explore combinations</summary><label>Search occupations<input id="role-search" type="search" placeholder="Software developer, nurse, film editor…" maxlength="100" autocomplete="off"></label>
 <div class="preference-grid">${selector('Occupational family','role-group',m.occupationGroups)}${selector('Field','role-discipline',m.disciplines)}${selector('Activity','role-activity',m.activities)}</div>
 <p class="muted">Field + activity narrows the catalogue. Select an actual role below to confirm it; selecting fields alone never invents a combined role.</p><div id="role-results" class="preference-results" aria-label="Occupation suggestions" aria-live="polite"></div></details>
 <small>Occupation reference: <a href="https://www.onetcenter.org/database.html" target="_blank" rel="noopener">O*NET 31.0</a>, adapted and supplemented by Aura. US occupational taxonomy with alternative titles; not an exhaustive worldwide classification.</small></fieldset>
 <fieldset><legend>Optional exclusions</legend><p class="muted">Exclude a specific unwanted role, not every unrelated industry. For example, “teaching” removes teaching roles from music results. An employer’s sector alone does not determine your occupation.</p><div id="exclude-chips" class="preference-chips"></div><div class="preference-inline"><label>Word or phrase<input id="exclude-text" maxlength="100" placeholder="e.g. teaching"></label><label>Look in<select id="exclude-scope"><option value="title">Job title</option><option value="description">Title and description</option></select></label><button type="button" data-pref="exclude-add">Add</button></div></fieldset>
 ${checks('Working arrangements','workModes',['remote','hybrid','onsite'],p.workModes)}${checks('Employment type','employmentTypes',['full-time','part-time','contract','freelance','internship'],p.employmentTypes)}
 ${checks('Contract basis','contractTerms',['permanent','fixed-term','temporary','zero-hours'],p.contractTerms??(p.permanentOnly?['permanent']:['permanent','fixed-term','temporary',...(p.allowZeroHours?['zero-hours']:[])]))}
 ${checks('Hiring channel','hiringChannels',['direct','agency'],p.hiringChannels??['direct','agency'])}${checks('Seniority','seniority',['entry','junior','graduate','mid','senior','lead'],p.seniority)}
 <fieldset><legend>Countries & locations</legend><label>Eligible countries<input type="search" id="country-search" placeholder="Type a country, then select it" autocomplete="off"></label><div id="country-chips" class="preference-chips"></div><div id="country-results" class="preference-results" aria-live="polite"></div><small>Search eligibility only; this does not assert citizenship or a legal right to work. No selection means no country filter.</small>
 <div class="preference-grid"><label>City or town<input type="search" id="place-search" placeholder="Type a place, then select it" maxlength="80" autocomplete="off"></label><label>Search places in<select id="place-country"><option value="">All countries</option>${pick((m.countries??[]).map(c=>[c.id,c.label]),'')}</select></label></div><div id="place-chips" class="preference-chips"></div><div id="place-results" class="preference-results" aria-live="polite"></div><button type="button" data-pref="custom-place">Add the typed place as a custom location</button><small class="data-attribution">Place suggestions: <a href="https://www.geonames.org/" target="_blank" rel="noopener">GeoNames</a> (CC BY 4.0), major towns/cities. Missing places can be explicitly added as custom, unverified locations.</small></fieldset>
 <fieldset><legend>Pay & paid hours</legend><div class="preference-grid"><label>Minimum gross pay<input name="payAmount" type="number" min="0" max="100000000" step=".01" value="${pay.amount}"></label><label>Currency<select name="payCurrency">${pick(currencyCodes.map(x=>[x,x]),pay.currency)}</select></label><label>Per<select name="payPeriod">${pick(['hour','day','week','fortnight','month','year'].map(x=>[x,x]),pay.period)}</select></label></div>
 <h3>Preferred paid hours</h3><input type="hidden" name="useHours" value="1"><div id="hours-fields"><div class="preference-grid"><label>Minimum paid hours/week (optional)<input name="hoursMinimum" type="number" min="1" max="168" step=".25" placeholder="No minimum" value="${hours.minimum??''}"></label><label>Maximum paid hours/week (optional)<input name="hoursMaximum" type="number" min="1" max="168" step=".25" placeholder="No maximum" value="${hours.maximum??''}"></label><label>Typical paid hours/day (for daily pay)<input name="hoursDaily" type="number" min="1" max="24" step=".25" placeholder="Not specified" value="${hours.daily??''}"></label><label>Paid weeks/year (calculation)<input name="paidWeeks" type="number" min="1" max="52" step=".5" value="${hours.paidWeeks}"></label></div><p class="muted">Leave both weekly limits blank for any hours, or set just one boundary. Blank is not zero and never overrides legal restrictions. The calculator uses your boundaries, or a labelled statistical reference if both are blank.</p><div class="preference-grid"><label>Work country (for guidance)<select name="hoursCountry"><option value="">Not specified</option>${pick((m.countries??[]).map(c=>[c.id,c.label]),hours.country)}</select></label><label>Age band<select name="ageBand">${pick([['unspecified','Not specified'],['adult','18 or older'],['young-worker','Under 18, above school-leaving age'],['school-age','Below compulsory school-leaving age']],hours.ageBand)}</select></label></div><p id="hours-guidance" class="muted"></p><output id="pay-equivalents" class="pay-equivalents" aria-live="polite"></output><p class="muted">Gross planning estimates, before tax and deductions. Paid weeks include paid leave. Contracted hours override your estimate when known. Missing hours or salary estimates stay flagged for review; currencies are never silently converted.</p></div></fieldset>
 <fieldset><legend>Weekly availability</legend><label>Timezone<select name="availabilityTimezone">${pick(tz.map(x=>[x,x]),availability.timezone)}</select></label><p class="muted">Any time, unavailable, or up to four time ranges per day. Split overnight availability across two days. Availability is not a declaration of legal working-time compliance.</p>${availability.days.map(d=>`<div class="availability-day" data-day="${d.day}"><div class="preference-inline"><b>${label(d.day)}</b><select aria-label="${d.day} availability" data-availability-mode>${pick([['any','Any time'],['unavailable','Unavailable'],['times','Specific times']],d.mode)}</select></div><div class="availability-times" ${d.mode==='times'?'':'hidden'}>${(d.intervals.length?d.intervals:[{start:'09:00',end:'17:00'}]).map(t=>timeRow(d.day,t)).join('')}<button type="button" data-pref="time-add">Add time range</button></div></div>`).join('')}</fieldset>
 <details class="preference-mapping"><summary>How preferences reach job sources</summary><p>Native filters are used only where the provider documents them. Aura checks returned listings using the same saved preferences. Unknown details remain unknown; blocked or unconnected sources are not represented as live searches.</p>${(m.providerFilters??[]).map(x=>`<p><b>${escape(x.name)}</b> ${escape(x.native)} <span class="muted">Aura checks: ${escape(x.local)}</span> <a href="${escape(x.documentation)}" target="_blank" rel="noopener">Provider documentation ↗</a></p>`).join('')}<p>Discovery explores recent related roles more broadly; Opportunities applies your saved choices. Explicit exclusions apply in both views. Existing applications and approvals are not cancelled when search preferences change.</p></details><p id="preference-error" role="alert" class="warn"></p>`;
 function timeRow(day,t){return `<div class="time-range"><input type="time" aria-label="${day} start" data-start value="${escape(t.start)}"><span>to</span><input type="time" aria-label="${day} end" data-end value="${escape(t.end)}"><button type="button" data-pref="time-remove" aria-label="Remove time range">×</button></div>`;}
 const find=s=>form.querySelector(s),error=text=>{find('#preference-error').textContent=text;};
 function chips(){for(const [id,items,kind] of [['role-chips',roles,'role'],['place-chips',places,'place'],['country-chips',countries.map(x=>({label:x})),'country'],['exclude-chips',exclusions.map(x=>({label:x.phrase+' · '+(x.scope==='title'?'title':'title + description')})),'exclude']])find('#'+id).innerHTML=items.map((x,i)=>`<span class="preference-chip">${escape(x.label)}<button type="button" data-pref="remove" data-kind="${kind}" data-index="${i}" aria-label="Remove ${escape(x.label)}">×</button></span>`).join('');}
 async function suggestions(kind){
  const token=++requests[kind],container=find(kind==='roles'?'#role-results':'#place-results');container.textContent='Searching…';
  try{const response=await api('/preferences/options',kind==='roles'?{kind,query:find('#role-search').value,group:find('#role-group').value,discipline:find('#role-discipline').value,activity:find('#role-activity').value}:{kind,query:find('#place-search').value,country:find('#place-country').value});
   if(token!==requests[kind]||!form.isConnected)return;results[kind]=new Map(response.options.map(x=>[x.id,x]));container.innerHTML=response.options.map(x=>`<button type="button" data-pref="pick-${kind}" data-id="${escape(x.id)}"><b>${escape(x.label)}</b>${x.examples?`<small>${escape(x.examples.join(' · '))}</small>`:''}</button>`).join('')||'<p class="muted">No matching suggestion. Try a different search or broaden the filters.</p>';
  }catch(e){if(token===requests[kind]&&form.isConnected)container.textContent=e.message;}
 }
 function countrySuggestions(){const q=find('#country-search').value.trim().toLowerCase();find('#country-results').innerHTML=q?(m.countries??[]).filter(c=>(c.label.toLowerCase().includes(q)||c.id.toLowerCase()===q||(q==='uk'&&c.id==='GB'))&&!countries.includes(c.label)).slice(0,12).map(c=>`<button type="button" data-pref="pick-country" data-id="${c.id}">${escape(c.label)}</button>`).join(''):'';}
 function calculator(){
  const get=n=>form.elements[n].value;
  const minimum=get('hoursMinimum')?+get('hoursMinimum'):null,maximum=get('hoursMaximum')?+get('hoursMaximum'):null,daily=+get('hoursDaily'),weeks=+get('paidWeeks'),amount=+get('payAmount'),period=get('payPeriod'),country=get('hoursCountry'),age=get('ageBand');
  const uk=country==='GB',weekMax=uk?({adult:48,'young-worker':40,'school-age':12}[age]??168):168,dayMax=uk?({'young-worker':8,'school-age':2}[age]??24):24;
  form.elements.hoursMinimum.max=weekMax;form.elements.hoursMaximum.max=weekMax;form.elements.hoursDaily.max=dayMax;
  const explanation=!uk?'Local working-time rules are not verified here. Check age, rest, night-work, permits and sector rules.':age==='adult'?'UK standard: normally 48 hours/week averaged over 17 weeks. This planner stays within that standard; it does not process opt-outs or sector exceptions.':age==='young-worker'?'UK under-18s above school-leaving age: normally no more than 8 hours/day and 40 hours/week. Rest and night-work restrictions also apply.':age==='school-age'?'Conservative UK term-time plan: up to 12 hours/week, 2 hours/day. School hours, age, specific days, local permits/bylaws and holiday rules still need separate checks.':'Choose an age band for guidance. Your age is not inferred.';
  find('#hours-guidance').innerHTML=escape(explanation)+' Legal working time may also include unpaid duties and hours across multiple jobs; this paid-hours calculator cannot establish compliance.'+(uk?' <a href="https://www.gov.uk/'+(age==='school-age'?'child-employment/restrictions-on-child-employment':'maximum-weekly-working-hours')+'" target="_blank" rel="noopener">Official guidance ↗</a>':'');
  if(!(weeks>0)||minimum>weekMax||maximum>weekMax||daily>dayMax||(minimum!==null&&maximum!==null&&minimum>maximum)||(period==='day'&&!daily)){find('#pay-equivalents').textContent='Check your hour limits and add paid hours/day for a daily-pay calculation.';return;}
  const bounds=[...new Set([minimum,maximum].filter(x=>x!==null))];let basis='Your chosen boundary/boundaries; missing limits stay open.';
  if(!bounds.length){
   if(['young-worker','school-age'].includes(age)||!m.hoursBenchmark){find('#pay-equivalents').textContent='Any hours preference. Enter a boundary to estimate pay; no adult-hours average is assumed for a young worker.';return;}
   const types=new FormData(form).getAll('employmentTypes'),key=types.length===1&&types[0]==='full-time'?'fullTime':types.length===1&&types[0]==='part-time'?'partTime':'allEmployees',b=m.hoursBenchmark;
   bounds.push(b[key]);basis=`Illustrative UK ${key==='fullTime'?'full-time':key==='partTime'?'part-time':'all-employee'} median basic paid hours: ${b[key]}/week (${b.period}). Not a local or personal guarantee; no hours filter added.`;
  }
  const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:get('payCurrency'),maximumFractionDigits:2}).format(n);
  find('#pay-equivalents').textContent=bounds.map(weekly=>{const annual=period==='hour'?amount*weekly*weeks:period==='day'?amount/daily*weekly*weeks:period==='week'?amount*weeks:period==='fortnight'?amount*weeks/2:period==='month'?amount*12:amount;return `At ${weekly} hours/week: ${money(annual)}/year · ${money(annual/12)}/month · ${money(annual/weeks/weekly)}/paid hour`;}).join('\n')+'\n'+basis;
  if(m.hoursBenchmark){const source=document.createElement('a');source.href=m.hoursBenchmark.url;source.target='_blank';source.rel='noopener';source.textContent='ONS paid-hours reference ↗';find('#pay-equivalents').append(document.createElement('br'),source);}
 }
 function bind(node){form=node;chips();calculator();
  find('#role-picker').addEventListener('toggle',()=>{if(find('#role-picker').open)suggestions('roles');});
  form.addEventListener('input',e=>{const id=e.target.id;if(['role-search','place-search'].includes(id)){const kind=id==='role-search'?'roles':'locations';clearTimeout(timers[kind]);++requests[kind];timers[kind]=setTimeout(()=>suggestions(kind),300);}if(id==='country-search')countrySuggestions();if(e.target.name)calculator();});
  form.addEventListener('change',e=>{if(e.target.id.startsWith('role-'))suggestions('roles');if(e.target.id==='place-country')suggestions('locations');if(e.target.matches('[data-availability-mode]'))e.target.closest('[data-day]').querySelector('.availability-times').hidden=e.target.value!=='times';calculator();});
  form.addEventListener('keydown',e=>{if(e.key==='Enter'&&['exclude-text','country-search','place-search','role-search'].includes(e.target.id)){e.preventDefault();if(e.target.id==='exclude-text')find('[data-pref="exclude-add"]').click();else{const container=find(e.target.id==='country-search'?'#country-results':e.target.id==='place-search'?'#place-results':'#role-results');container.querySelector('button')?.focus();}}if(e.key==='Escape'){for(const kind of ['roles','locations']){++requests[kind];clearTimeout(timers[kind]);}find('#country-results').replaceChildren();find('#place-results').replaceChildren();find('#role-picker').open=false;}});
  form.addEventListener('click',e=>{const b=e.target.closest('[data-pref]');if(!b)return;e.preventDefault();error('');const action=b.dataset.pref;
   if(action==='remove'){({role:roles,place:places,country:countries,exclude:exclusions})[b.dataset.kind].splice(+b.dataset.index,1);chips();return;}
   if(action==='pick-roles'||action==='pick-locations'){const item=results[action==='pick-roles'?'roles':'locations'].get(b.dataset.id),list=action==='pick-roles'?roles:places;if(item&&!list.some(x=>x.id===item.id))list.push(item);chips();return;}
   if(action==='pick-country'){const item=(m.countries??[]).find(c=>c.id===b.dataset.id);if(item&&!countries.includes(item.label))countries.push(item.label);find('#country-search').value='';countrySuggestions();chips();return;}
   if(action==='custom-place'){const name=find('#place-search').value.trim();if(name.length<2){error('Type the place name first.');return;}if(!places.some(x=>x.id==='custom:'+name))places.push({id:'custom:'+name,name,label:name+' (custom)'});chips();return;}
   if(action==='exclude-add'){const phrase=find('#exclude-text').value.trim(),scope=find('#exclude-scope').value;if(phrase.length<2){error('Enter a word or phrase of at least two characters.');return;}if(!exclusions.some(x=>x.phrase.toLowerCase()===phrase.toLowerCase()&&x.scope===scope))exclusions.push({phrase,scope});find('#exclude-text').value='';chips();return;}
   if(action==='time-add'){const box=b.parentElement;if(box.querySelectorAll('.time-range').length>=4){error('Up to four time ranges per day.');return;}b.insertAdjacentHTML('beforebegin',timeRow(b.closest('[data-day]').dataset.day,{start:'18:00',end:'20:00'}));}
   if(action==='time-remove')b.closest('.time-range').remove();
  });
 }
 function read(){const data=new FormData(form),get=n=>String(data.get(n)??''),list=n=>data.getAll(n);if(!roles.length)throw new Error('Choose at least one occupation.');
  for(const n of ['workModes','employmentTypes','contractTerms','hiringChannels','seniority'])if(!list(n).length)throw new Error('Choose at least one '+label(n)+' option.');
  const result={...p,roleTargets:roles.map(r=>r.id),locationIds:places.filter(x=>!x.id.startsWith('custom:')).map(x=>x.id),customLocations:places.filter(x=>x.id.startsWith('custom:')).map(x=>x.name),countries:[...countries],exclusions:[...exclusions],pay:{amount:+get('payAmount'),currency:get('payCurrency'),period:get('payPeriod')},availability:{timezone:get('availabilityTimezone'),days:[...form.querySelectorAll('[data-day]')].map(row=>({day:row.dataset.day,mode:row.querySelector('[data-availability-mode]').value,intervals:row.querySelector('[data-availability-mode]').value==='times'?[...row.querySelectorAll('.time-range')].map(range=>({start:range.querySelector('[data-start]').value,end:range.querySelector('[data-end]').value})):[]}))}};
  for(const n of ['workModes','employmentTypes','contractTerms','hiringChannels','seniority'])result[n]=list(n);
  if(data.has('useHours'))result.workingHours={...(get('hoursMinimum')?{minimum:+get('hoursMinimum')}:{}),...(get('hoursMaximum')?{maximum:+get('hoursMaximum')}:{}),...(get('hoursDaily')?{daily:+get('hoursDaily')}:{}),paidWeeks:+get('paidWeeks'),country:get('hoursCountry'),ageBand:get('ageBand')};else delete result.workingHours;
  return result;
 }
 return {html,bind,read};
}};
